const handleUnhandledRejection = (server) => {
    process.on('unhandledRejection', (err) => {
        console.log('UNHANDLED REJECTION! ðŸ’¥ Shutting down...');
        console.log(err.name, err.message);
        server.close(() => {
            process.exit(1);
        });
    });
};

const handleUncaughtException = () => {
    process.on('uncaughtException', (err) => {
        console.log('UNCAUGHT EXCEPTION! ðŸ’¥ Shutting down...');
        console.log(err.name, err.message);
        process.exit(1);
    });
};

module.exports = {
    handleUnhandledRejection,
    handleUncaughtException
};
